name: Flinn
favicon: null
layout_spectrum: 0.6198246031999588
typography_spectrum: 0.41284024459309876
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.43300775601528585
  lightness: 0.07936180918477476
  saturation: 0.9972702665254474
  rhythmicContrast: 0.776073012733832
purpose: []
